### PR TITLE
a bunch of cleanups

### PR DESCRIPTION
**Pull request by spacejam**
fyi @spacekookie 

* completely nuke GPS code and tons of hyper deps (keeping it in protobuf to avoid data issues)
* update deps
* reformat some stuff
* fix compiler bug which is currently a warning

### CODE REVIEW

**Comment by spacejam** [comment]
I'm cleaning this up because I want to add a small batch of features afterward:
* a command line argument that allows merging multiple void files into a single one by simply rebasing all of the node ID's in one of them and merging them together
* a new tui command (C-m) for merging the children of a copied (C-y, already exists) node into the currently selected node
* a new tui command (C-o) for sorting all children of a selected node

**Comment by spacekookie** [comment]
I haven't actively used `void` in a while, but something I might still be interested in doing later down the line is swapping the storage backend for a non-binary format (I started working on https://github.com/spacekookie/g3f for that reason). I think we might have had a conversation about this before, but I don't really remember it anymore; is that something you'd be open to?  The code probably would need some re-structuring to allow the storage backend to be modular.

**Review by spacekookie — APPROVED** [review]

**Comment by spacejam** [comment]
Any new change just has to be able to speak the previous format at the same time, to avoid data loss for people who have stored years of their notes in void at this point. Would any problem that could be addressed by using a more bloated text serialization format be better solved with a simple function that dumps the current notes in json format, so people can use jq et al for using in a flexible way? I think anything non-binary should be json so people can use it with the extensive existing tooling that exists for json, but I'm hesitant to add serialization complexity when we have to keep the existing format around forever anyway to avoid breaking people's workflows if they upgrade.

**Comment by spacekookie** [comment]
> Any new change just has to be able to speak the previous format at the same time, to avoid data loss for people who have stored years of their notes in void at this point.

Agreed. Although I don't really see why any new format that gets added needs to touch the old parsing code at all.

The reason why I was proposing an alternative format, and especially `g3f` was because I keep my `void.db` in a git repo and it would be cool to have tooling around being able to save changes as commits, but then having the commit diffs be meaningful to humans, not just binary noise.

**Pull request merged**
